import pyjokes
print("joke is the day is :"+pyjokes.get_joke())
print("joke of the day: "+"joke of the day: "+"joke of the day: "+"joke of the day: "+"joke of the day: "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : "+pyjokes.get_joke())
print("vey cool : j"+pyjokes.get_joke())

